development:
  adapter: sqlite3
  database: db/blog_comp_development.db 
    
test:
  adapter: sqlite3
  database: db/blog_comp_test.db

production:
  adapter: sqlite3
  database: db/blog_comp_production.db
