# development:
#   adapter: mysql
#   database: mack_blog_demo_development
#   host: localhost
#   username: root
#   password: 
#     
# test:
#   adapter: mysql
#   database: mack_blog_demo_test
#   host: localhost
#   username: root
#   password:
# 
# production:
#   adapter: mysql
#   database: mack_blog_demo_production
#   host: localhost
#   username: root
#   password:

development:
  adapter: sqlite3
  database: db/mack_blog_demo_development.db 

test:
  adapter: sqlite3
  database: db/mack_blog_demo_test.db 

production:
  adapter: sqlite3
  database: db/mack_blog_demo_production.db 
