# development:
#   default:
#     adapter: mysql
#     database: mack_blog_demo_development
#     host: localhost
#     username: root
#     password: 
#     
# test:
#   default:
#     adapter: mysql
#     database: mack_blog_demo_test
#     host: localhost
#     username: root
#     password:
# 
# production:
#   default:
#     adapter: mysql
#     database: mack_blog_demo_production
#     host: localhost
#     username: root
#     password:
  
development:
  default:
    adapter: postgres
    database: mack_blog_demo_development
    host: localhost
    username: ruby
    password: password

test:
  default:
    adapter: postgres
    database: mack_blog_demo_test
    host: localhost
    username: ruby
    password: password

production:
  default:
    adapter: postgres
    database: mack_blog_demo_production
    host: localhost
    username: ruby
    password: password

# development:
#   default:
#     adapter: sqlite3
#     database: db/mack_blog_demo_development.db 
# 
# test:
#   default:                           
#     adapter: sqlite3
#     database: db/mack_blog_demo_test.db 
# 
# production:
#   default:                                 
#     adapter: sqlite3
#     database: db/mack_blog_demo_production.db 
