development:
  adapter: mysql
  database: blog_comp_development
  host: localhost
  username: root
  password: 
    
test:
  adapter: mysql
  database: blog_comp_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: blog_comp_development
  host: localhost
  username: root
  password:
